# Generated by Django 4.2.23 on 2025-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='anio',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
