# Generated by Django 4.2.23 on 2025-07-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appventas', '0002_carro_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='anio',
            field=models.IntegerField(null=True),
        ),
    ]
