# Generated by Django 4.2.23 on 2025-07-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contactos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='columna2',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
