# Generated by Django 4.2.23 on 2025-07-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_contactos', '0002_contacto_columna2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='columna1',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='contacto',
            old_name='columna2',
            new_name='telefono',
        ),
    ]
