# Generated by Django 4.2.30 on 2026-08-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contactos', '0003_rename_columna1_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
