# Generated by Django 4.2.23 on 2025-07-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=40)),
                ('telefono', models.TextField(max_length=10)),
                ('detalle', models.TextField(max_length=100)),
            ],
        ),
    ]
