# Generated by Django 4.2.23 on 2025-07-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcontactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='detalle',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
